### PR TITLE
refactor: upgrade to inlang/core v0.7

### PR DESCRIPTION
**Pull request by samuelstroschein**
:)

### CODE REVIEW

**Comment by samuelstroschein** [comment]
if you merge this, make a new version release. this is a breaking change. thus, version 2

**Comment by felixhaeberle** [comment]
@samuelstroschein thanks, added github actions CI CD to test this.

**Comment by samuelstroschein** [comment]
@felixhaeberle could you add the ci actions to the plugin-template too?

**Comment by felixhaeberle** [comment]
@samuelstroschein yep 👍 thought so too.

**Pull request merged**
